npm audit check in ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: Run Tests on PR
+name: Run Tests and Audit on PR
 
 on:
   pull_request:
@@ -7,7 +7,7 @@ on:
       - main
 
 jobs:
-  test:
+  test-and-audit:
     runs-on: ubuntu-latest
 
     steps:
@@ -30,4 +30,17 @@ jobs:
           if [ $? -ne 0 ]; then
             echo "Unit tests failed. Commit rejected."
             exit 1
+          fi
+
+      - name: Run npm audit
+        run: npm audit --json > audit_results.json || true
+
+      - name: Check for Vulnerabilities
+        run: |
+          vulnerabilities=$(jq '.metadata.vulnerabilities' audit_results.json)
+          if [ "$vulnerabilities" != "null" ]; then
+            echo "Vulnerabilities found. Failing the check."
+            exit 1
+          else
+            echo "No vulnerabilities found."
           fi
