ci fix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,4 +26,8 @@ jobs:
         run: npm test
 
       - name: Check Unit Test Results
-        run: exit $(npm test)
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Unit tests failed. Commit rejected."
+            exit 1
+          fi
